security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    user1:  { password: userpass1, roles: [ 'ROLE_USER' ] }
                    user2:  { password: userpass2, roles: [ 'ROLE_USER' ] }
                    user3:  { password: userpass3, roles: [ 'ROLE_USER' ] }
                    user4:  { password: userpass4, roles: [ 'ROLE_USER' ] }
                    user5:  { password: userpass5, roles: [ 'ROLE_USER' ] }

    firewalls:
        login:
            pattern: ^/login$
            security: false
            anonymous: ~

        secured_area:
            pattern:    ^/
            ajax_form_login: ~

    access_control:
        - { path: ^/, roles: ROLE_USER }
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
