parameters:
#    lucian_bg_image.example.class: Lucian\BgImageBundle\Example

services:
#    lucian_bg_image.example:
#        class: %lucian_bg_image.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
